---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -v -cover ./...
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-amazon-secrets github.com/drone/drone-amazon-secrets/cmd/drone-amazon-secrets

- name: publish
  image: plugins/ecr
  settings:
    create_repository: true
    repo: drone-amazon-secrets-plain
    registry: 072805691757.dkr.ecr.us-east-1.amazonaws.com
    when:
      branch:
        - master
...